In [1]:
# -*- coding:utf-8 -*-

In [2]:
import numpy as np

## 多维数组

In [3]:
arr = np.array([i for i in range(10)])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr = np.arange(10)

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr = np.ones((3,3))

In [10]:
type(arr)

numpy.ndarray

In [11]:
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
arr = np.zeros((3,4))

In [13]:
type(arr)

numpy.ndarray

In [14]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
arr = np.empty((4,3))

In [16]:
type(arr)

numpy.ndarray

In [17]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
arr = np.array([ i*3 for i in range(10)])

In [19]:
arr.dtype

dtype('int32')

In [20]:
arr = np.array([ i*3 for i in range(10)], dtype=np.float32)

In [21]:
arr.dtype

dtype('float32')

In [22]:
arr1 = arr.astype(np.int32)

In [23]:
arr1.dtype

dtype('int32')

In [24]:
arr = np.arange(12).reshape(3,4)

In [25]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
arr[0]

array([0, 1, 2, 3])

In [27]:
arr[1:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
arr[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [29]:
arr[1,:]

array([4, 5, 6, 7])

In [30]:
arr[1,1:3]

array([5, 6])

In [31]:
arr[:,2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [32]:
arr[arr>=5]

array([ 5,  6,  7,  8,  9, 10, 11])

In [33]:
arr[(arr>5) & (arr<8)]

array([6, 7])

In [34]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
arr.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [36]:
arr = np.arange(12).reshape(2,3,2)

In [37]:
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [38]:
arr.transpose((1,0,2))

array([[[ 0,  1],
        [ 6,  7]],

       [[ 2,  3],
        [ 8,  9]],

       [[ 4,  5],
        [10, 11]]])

In [39]:
arr = np.arange(12).reshape(3,4)

In [40]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
np.sqrt(arr)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479]])

In [42]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
arr.sum()

66

In [44]:
arr.mean()

5.5

In [45]:
arr.std()

3.452052529534663

In [46]:
arr.var()

11.916666666666666

In [47]:
arr.min()

0

In [48]:
arr.max()

11

In [49]:
arr.argmin()

0

In [50]:
arr.argmax()

11

In [51]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66], dtype=int32)

In [52]:
arr.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [53]:
arr.sum(axis=0)

array([12, 15, 18, 21])

In [54]:
arr.sum(axis=1)

array([ 6, 22, 38])

In [55]:
np.all(arr>5)

False

In [56]:
np.any(arr>5)

True

In [57]:
np.unique(arr)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [61]:
text = np.loadtxt('test.txt', dtype=np.str)

In [62]:
text

array(['hello,world!', 'hello,world!', 'hello,world!', 'hello,world!',
       'hello,world!'], dtype='<U12')

In [65]:
np.savetxt('arr.txt',arr)

In [66]:
arr_text = np.loadtxt('arr.txt')

In [67]:
arr_text

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [69]:
from numpy.random import seed, shuffle, rand, randn,randint, normal

In [70]:
# 确定随机数生成器种子
seed(1000)

In [71]:
arr = np.arange(10)

In [72]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
shuffle(arr)

In [74]:
arr

array([2, 6, 5, 1, 4, 9, 0, 8, 7, 3])

In [75]:
rand(3,4)

array([[0.21233268, 0.04070962, 0.39719446, 0.2331322 ],
       [0.84174072, 0.20708234, 0.74246953, 0.39215413],
       [0.18225652, 0.74353941, 0.06958208, 0.8853372 ]])

In [76]:
randn(3,4)

array([[-0.4122031 , -0.07400906, -0.92893693,  1.39006147],
       [ 1.19506933,  0.70734239,  0.99296211,  0.13946394],
       [-0.08988248, -0.14974264,  0.4055338 , -0.75133127]])

In [77]:
randint(1,100, 50)

array([80, 18, 70, 55, 30, 12, 13,  6, 56, 89, 73, 19,  3, 78, 60, 42,  7,
       11, 36, 52, 54, 48, 57, 21, 66, 97, 26, 82, 73, 49,  3, 76, 74, 14,
       64, 20, 79, 59, 10,  7, 83, 86, 57, 28, 22, 55, 87, 77, 92, 28])

In [81]:
normal(size=(4,4))

array([[-0.68807121, -0.65081409, -1.39056886, -0.6103138 ],
       [ 0.94527684, -1.30086682, -1.35523819, -0.01107898],
       [ 1.05777734,  2.64977959, -0.24102242,  0.8592392 ],
       [ 0.99086392,  0.66431107,  1.34763727,  1.31283156]])

In [88]:
X = randn(4,4)

In [89]:
X

array([[-1.31501539, -0.24106312, -1.32740907, -0.37947457],
       [-0.42873954,  0.4299933 , -1.21497906,  0.01469969],
       [-0.06076035,  1.38813751, -0.09430998, -0.11141905],
       [-0.00440068, -0.39957698,  0.16934311, -0.03796476]])

In [90]:
Y = randn(4,4)

In [91]:
Y

array([[-1.06523207, -0.58166801,  0.4359142 , -1.1371945 ],
       [ 0.24014359, -1.54559544, -1.26752451, -0.57649947],
       [ 0.04742347,  0.35103028,  1.79078511, -1.54737168],
       [ 2.15460726,  2.21782268, -2.49866394,  1.93286391]])

In [95]:
from numpy.linalg import inv,det,eig,qr,svd

In [96]:
det(X)

0.0377328521388211

In [97]:
X.dot(Y)

array([[ 0.46233779, -0.17007964, -1.69660545,  2.95492353],
       [ 0.53402076, -0.80910474, -2.94441668,  2.14810602],
       [ 0.15353939, -2.39037002, -1.67647477, -0.80058946],
       [-0.16503641,  0.59538954,  0.90267359, -0.1000571 ]])

In [98]:
inv(X)

array([[ -2.79774745,   5.54866033,   3.50364428,  19.83062334],
       [  0.20075305,  -0.61079247,   0.16195446,  -2.71841428],
       [  1.09580975,  -3.09421488,  -1.27329426,  -8.41429483],
       [  3.09928277,  -8.01646678,  -7.79025862, -37.55997175]])

In [99]:
eig(X)

(array([-1.20081138+0.j       ,  0.10378577+1.1381607j,
         0.10378577-1.1381607j, -0.024057  +0.j       ]),
 array([[ 0.97561139+0.j        , -0.38801677+0.24510306j,
         -0.38801677-0.24510306j, -0.46629375+0.j        ],
        [ 0.15582662+0.j        ,  0.06341354+0.54793481j,
          0.06341354-0.54793481j,  0.05861725+0.j        ],
        [-0.13418485+0.j        ,  0.66505236+0.j        ,
          0.66505236-0.j        ,  0.19686112+0.j        ],
        [ 0.07677828+0.j        , -0.18077075-0.10070224j,
         -0.18077075+0.10070224j,  0.86045328+0.j        ]]))

In [100]:
qr(X)

(array([[-0.94982388,  0.13547571, -0.27067504, -0.07884126],
        [-0.30967474, -0.28914007,  0.88256061,  0.20392729],
        [-0.04388666, -0.91077384, -0.35957265,  0.19817288],
        [-0.00317857,  0.26179261, -0.13612237,  0.95547121]]),
 array([[ 1.38448339,  0.03615881,  1.64065385,  0.36089237],
        [ 0.        , -1.52587212,  0.30169528,  0.0358788 ],
        [ 0.        ,  0.        , -0.70213626,  0.16091875],
        [ 0.        ,  0.        ,  0.        , -0.02543855]]))

In [101]:
svd(X)

(array([[-0.81854455,  0.30887999, -0.47550356, -0.09205613],
        [-0.55656359, -0.22681418,  0.76771998,  0.22225737],
        [-0.12099923, -0.88683945, -0.40424341,  0.18831419],
        [ 0.07470591,  0.25819423, -0.14522282,  0.95218963]]),
 array([2.25744287, 1.52818566, 0.49833617, 0.02194847]),
 array([[ 0.58563728, -0.10623172,  0.79152344,  0.13868832],
        [-0.16764278, -0.9856209 , -0.00462928, -0.02063733],
        [ 0.64483306, -0.11714368, -0.57801192,  0.48617887],
        [ 0.46164402, -0.05952824, -0.19842236, -0.86253681]]))

In [102]:
X.T

array([[-1.31501539, -0.42873954, -0.06076035, -0.00440068],
       [-0.24106312,  0.4299933 ,  1.38813751, -0.39957698],
       [-1.32740907, -1.21497906, -0.09430998,  0.16934311],
       [-0.37947457,  0.01469969, -0.11141905, -0.03796476]])

In [103]:
arr

array([2, 6, 5, 1, 4, 9, 0, 8, 7, 3])

In [104]:
arr.shape

(10,)

## 广播

In [3]:
arr = np.arange(5)

In [4]:
arr

array([0, 1, 2, 3, 4])

In [5]:
arr*4

array([ 0,  4,  8, 12, 16])

In [8]:
arr = np.random.randn(4,3)

In [9]:
arr.mean(axis=0)

array([-0.32616492, -0.03680105, -0.32370606])

In [10]:
demeaned = arr - arr.mean(axis=0)

In [11]:
demeaned

array([[-0.48406504,  0.31141395, -0.09457933],
       [ 0.14758052, -2.15465162, -0.38443962],
       [ 0.42445634,  0.53251846,  0.49934457],
       [-0.08797182,  1.31071921, -0.02032562]])

In [12]:
arr

array([[-0.81022996,  0.2746129 , -0.41828539],
       [-0.1785844 , -2.19145267, -0.70814568],
       [ 0.09829142,  0.49571741,  0.17563851],
       [-0.41413674,  1.27391816, -0.34403168]])

In [13]:
row_means = arr.mean(axis=1)

In [14]:
row_means

array([-0.31796748, -1.02606092,  0.25654911,  0.17191658])

In [15]:
row_means.reshape(4,1)

array([[-0.31796748],
       [-1.02606092],
       [ 0.25654911],
       [ 0.17191658]])

In [16]:
demeaned = arr - row_means.reshape(4,1)

In [17]:
demeaned

array([[-0.49226248,  0.59258038, -0.10031791],
       [ 0.84747652, -1.16539175,  0.31791523],
       [-0.15825769,  0.23916829, -0.0809106 ],
       [-0.58605332,  1.10200158, -0.51594825]])

In [18]:
demeaned.mean(axis=1)

array([-3.70074342e-17,  0.00000000e+00,  0.00000000e+00,  3.70074342e-17])

In [19]:
arr = np.arange(10)

In [20]:
np.add.reduce(arr)

45

In [21]:
arr.sum()

45

In [22]:
arr = np.random.randn(5,5)

In [23]:
arr[::2].sort(axis=1)

In [24]:
arr[:,:-1] < arr[:,1:]

array([[ True,  True,  True,  True],
       [ True, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [ True,  True,  True,  True]])

In [25]:
np.logical_and.reduce(arr[:,:-1] < arr[:,1:], axis=1)

array([ True, False,  True, False,  True])

In [26]:
arr = np.arange(15).reshape((3,5))

In [27]:
np.add.accumulate(arr, axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]], dtype=int32)

In [28]:
arr = np.arange(3).repeat([1,2,2])

In [29]:
arr

array([0, 1, 1, 2, 2])

In [30]:
np.multiply.outer(arr, np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [31]:
result = np.subtract.outer(np.random.randn(3,4), np.random.randn(5))

In [32]:
result.shape

(3, 4, 5)

In [33]:
arr = np.arange(10)

In [34]:
np.add.reduceat(arr, [0, 5, 8])

array([10, 18, 17], dtype=int32)

In [35]:
arr = np.multiply.outer(np.arange(4),np.arange(5))

In [36]:
arr

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [37]:
np.add.reduceat(arr, [0, 2, 4], axis=1)

array([[ 0,  0,  0],
       [ 1,  5,  4],
       [ 2, 10,  8],
       [ 3, 15, 12]], dtype=int32)

In [38]:
def add_elem(x, y):
    return x + y

In [39]:
add_them = np.frompyfunc(add_elem, 2, 1)

In [41]:
add_them(np.arange(8), np.arange(8))

array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

In [42]:
add_them2 = np.vectorize(add_elem, otypes=[np.float64])

In [43]:
add_them2(np.arange(8), np.arange(8))

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])